server :
  port : 8095
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800
      
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/shop?serverTimezone=UTC
      username: root
      password: a1234
      driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: kkt09072@gmail.com
    password: password
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

mybatis:
  config : mybatis-config.xml
  mapper-locations: mapper/*Mapper.xml

file:
  dir: /Users/kim6/Desktop/file/